platform :ios, '9.0'

target 'JRChatTest' do
use_frameworks!

	pod 'AFNetworking'
	pod 'hpple'
    pod 'MBProgressHUD',    '1.1.0'
    pod 'YYModel'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'YYText'
    pod 'SobotKit'
  
end
